import React from 'react';

import * as S from './style';

const Desc = props => {
  return (
    <S.Container>
      A LOT OF LOREM IPSUM. A LOT OF LOREM IPSUM. A LOT OF LOREM IPSUM. A LOT OF
      LOREM IPSUM. A LOT OF LOREM IPSUM. A LOT OF LOREM IPSUM. A LOT OF LOREM
      IPSUM. A LOT OF LOREM IPSUM. A LOT OF LOREM IPSUM. A LOT OF LOREM IPSUM. A
      LOT OF LOREM IPSUM. A LOT OF LOREM IPSUM. A LOT OF LOREM IPSUM. A LOT OF
      LOREM IPSUM. A LOT OF LOREM IPSUM. A LOT OF LOREM IPSUM. A LOT OF LOREM
      IPSUM. A LOT OF LOREM IPSUM. A LOT OF LOREM IPSUM. A LOT OF LOREM IPSUM. A
      LOT OF LOREM IPSUM. A LOT OF LOREM IPSUM. A LOT OF LOREM IPSUM. A LOT OF
      LOREM IPSUM. A LOT OF LOREM IPSUM. A LOT OF LOREM IPSUM. A LOT OF LOREM
      IPSUM. A LOT OF LOREM IPSUM. A LOT OF LOREM IPSUM. A LOT OF LOREM IPSUM. A
      LOT OF LOREM IPSUM. A LOT OF LOREM IPSUM. A LOT OF LOREM IPSUM. A LOT OF
      LOREM IPSUM. A LOT OF LOREM IPSUM. A LOT OF LOREM IPSUM. A LOT OF LOREM
      IPSUM. A LOT OF LOREM IPSUM. A LOT OF LOREM IPSUM. A LOT OF LOREM IPSUM.
    </S.Container>
  );
};

export default Desc;
